def generate_spice_netlist(ir):
    netlist = ".title Generated by Hydralog\n"
    for comp_type, name, params in ir.components:
        if comp_type == "filter":
            netlist += f"X{name} {name}_in {name}_out {comp_type.upper()} fc={params.get('fc', 1000)}\n"
    for src, dst in ir.connections:
        netlist += f"* Connect {src} to {dst}\nW{src}_{dst} {src} {dst}\n"
    netlist += ".end\n"
    return netlist